version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db

  backend:
    build: ./auth-backend
    ports:
      - "5000:5000"
    volumes:
      - logs:/app/logs
      - ./auth-backend:/app
      - /app/node_modules
    depends_on:
      - mongodb

  todo:
    build: ./todo
    ports:
      - "3000:3000"
    volumes:
      - ./todo/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
